# Site settings
# =============
#
# permalink: /:title	- remove the date from the uri
#

title: GitPage
email: office@donvercety.biz
description: >
  Coding tutorials, scripts, libraries and how to's for all that is code

baseurl: "" # the subpath of your site, e.g. /blog/					

# url: "http://localhost:4000"
url: "http://donvercety.github.io" 		

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

# Bootstrap Skins ( http://bootswatch.com/ )
skins:
  - skin: /css/bootstrap.slate.css
    name: Slate

  - skin: /css/bootstrap.darkly.css
    name: Darkly

  - skin: /css/bootstrap.simplex.css
    name: Simplex

  - skin: /css/bootstrap.yeti.css
    name: Yeti

  - skin: /css/bootstrap.united.css
    name: United

  - skin: /css/bootstrap.superhero.css
    name: Superhero

  - skin: /css/bootstrap.sandstone.css
    name: Sandstone