# Site settings
# =============
#
# permalink: /:title	- remove the date from the uri
#

title: donvercety GitHub Page
email: office@donvercety.biz
description: >
  Coding tutorials, scripts, libraries and how to's for all that is code

baseurl: ""							# the subpath of your site, e.g. /blog/
url: "http://donvercety.github.io" 		# the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

# Bootstrap Skins ( http://bootswatch.com/ )
skins:
  - skin: /css/bootstrap.slate.css
    name: Slate

  - skin: /css/bootstrap.darkly.css"
    name: Darkly
